// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_tokens (id, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING id, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateTokenParams struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.ID, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getToken = `-- name: GetToken :one
SELECT id, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens WHERE id = $1
`

func (q *Queries) GetToken(ctx context.Context, id string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const markTokenRevoked = `-- name: MarkTokenRevoked :exec
UPDATE refresh_tokens
SET
    updated_at = $1,
    revoked_at = $1
WHERE id = $2
`

type MarkTokenRevokedParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) MarkTokenRevoked(ctx context.Context, arg MarkTokenRevokedParams) error {
	_, err := q.db.ExecContext(ctx, markTokenRevoked, arg.UpdatedAt, arg.ID)
	return err
}
